apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-p5ic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-p5ic
    app.kubernetes.io/part-of: tkrw-pr714-0075-0018-app
  name: devfile-sample-p5ic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-p5ic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-p5ic
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0018-tenant/tkrw-pr714-0075-0018-app/devfile-sample-p5ic@sha256:f025c4fb6beadc61ccd9d40ebd0af9cd94e4497f0d2bc99f7e4fcc286c65348d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
