apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-p5ic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0018-tenant/tkrw-pr714-0075-0018-app/devfile-sample-p5ic@sha256:f025c4fb6beadc61ccd9d40ebd0af9cd94e4497f0d2bc99f7e4fcc286c65348d
        name: my-nodejs
        resources: {}
status: {}
